# iHMP Analysis Pipeline Configuration

# Input/Output Paths
paths:
  data_dir: "/Users/reneeoles/Desktop/input"
  log_dir: "/Users/reneeoles/Desktop/input/logs"

# Snakemake Configuration
snakemake:
  cores: 4
  memory: "32G"
  conda_env: "snakemake/envs/instrain.yml"
  rules:
    - "snakemake/rules/assembly.smk"
    - "snakemake/rules/mapping.smk"
    - "snakemake/rules/variant_calling.smk"

# Python Analysis Parameters
python:
  min_coverage: 10
  min_quality: 20
  min_frequency: 0.01
  max_frequency: 0.99
  min_reads: 5
  threads: 4
  p_threshold: 0.05

# R Analysis Parameters
r:
  significance_threshold: 0.05
  min_samples: 3
  plot_theme: "minimal"
  figure_dpi: 300
  figure_width: 10
  figure_height: 8

# Reference Data
reference:
  bakta_db: "data/reference/bakta_db"

# Metadata files
metadata:
  file: "/Users/reneeoles/Desktop/input/hmp2_metadata_2018-08-20.csv"

# Logging
logging:
  level: "INFO"
  file: "pipeline.log"
  max_size: "100MB"
  backup_count: 3

# Analysis parameters
params:
  # InStrain
  min_coverage: 5
  min_freq: 0.1
  min_scaffold_length: 1000
  min_scaffold_coverage: 5.0
  min_scaffold_breadth: 0.4
  
  # SNP tracking
  snp_tracking:
    min_coverage: 10
    min_freq: 0.05
    p_threshold: 0.05
    min_freq_change: 0.1
    min_trajectory_change: 0.2
    min_slope: 0.01
    min_abs_change: 0.1

# Conda environments
conda_envs:
  qc: "envs/qc.yaml"
  assembly: "envs/assembly.yaml"
  mapping: "envs/mapping.yaml"
  mags: "envs/mags.yaml"
  annotation: "envs/annotation.yaml"
  instrain: "envs/instrain.yaml"

# Resource limits
resources:
  threads: 8
  memory: "32G"
  time: "24:00:00"

# Test patient
patients: ["M2069"] 