name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
    
    - name: Install dependencies
      run: |
        conda env create -f snakemake/envs/instrain.yml
        Rscript -e "renv::restore()"
    
    - name: Run Python tests
      run: |
        source activate instrain
        pytest tests/python/
    
    - name: Run R tests
      run: Rscript -e "testthat::test_dir('tests/r/')"

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t ihmp-pipeline .
    
    - name: Test Docker image
      run: |
        docker run --rm ihmp-pipeline --version
        docker run --rm ihmp-pipeline --help

  deploy:
    needs: build-docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker build -t roles/ihmp-pipeline:latest .
        docker push roles/ihmp-pipeline:latest 